# Generated by Django 5.2.6 on 2025-09-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do Item"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "local_armazenamento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Local de Armazenamento",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do setor", max_length=100, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_necessaria",
                    models.PositiveIntegerField(verbose_name="Quantidade Necessária"),
                ),
                (
                    "item_estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.itemestoque",
                        verbose_name="Componente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do Produto"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Produto"
                    ),
                ),
                (
                    "componentes",
                    models.ManyToManyField(
                        related_name="produtos_fabricados",
                        through="core.Componente",
                        to="core.itemestoque",
                        verbose_name="Lista de Componentes",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="componente",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.produtofabricado"
            ),
        ),
        migrations.CreateModel(
            name="SaidaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Enviada"),
                ),
                ("cliente", models.CharField(max_length=200, verbose_name="Cliente")),
                (
                    "nota_fiscal",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notas_fiscais/",
                        verbose_name="Nota Fiscal",
                    ),
                ),
                (
                    "foto_saida",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_saidas/",
                        verbose_name="Foto da Saída",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Saída"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.produtofabricado",
                        verbose_name="Produto Enviado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável pela Saída",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_recebida",
                    models.PositiveIntegerField(verbose_name="Quantidade Recebida"),
                ),
                (
                    "foto_documento",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_documentos/",
                        verbose_name="Foto do Documento",
                    ),
                ),
                (
                    "foto_embalagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_embalagens/",
                        verbose_name="Foto da Embalagem",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Recebimento"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.itemestoque",
                        verbose_name="Item Recebido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.setor",
                        verbose_name="Setor de Alocação",
                    ),
                ),
            ],
        ),
    ]
