# Generated by Django 5.2.6 on 2025-09-22 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do Item"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "local_armazenamento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Local de Armazenamento",
                    ),
                ),
                (
                    "documentacao",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentos_itens/",
                        verbose_name="Documentação",
                    ),
                ),
                (
                    "foto_principal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_itens/",
                        verbose_name="Foto Principal",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do setor", max_length=100, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_itens/")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.itemestoque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_necessaria",
                    models.PositiveIntegerField(verbose_name="Quantidade Necessária"),
                ),
                (
                    "item_estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.itemestoque",
                        verbose_name="Componente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do Produto"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Produto"
                    ),
                ),
                (
                    "componentes",
                    models.ManyToManyField(
                        related_name="produtos_fabricados",
                        through="core.Componente",
                        to="core.itemestoque",
                        verbose_name="Lista de Componentes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_produtos/")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.produtofabricado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.FileField(upload_to="documentos_produtos/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Manual de Instruções"),
                            ("instalacao", "Guia de Instalação"),
                            ("manutencao", "Guia de Manutenção"),
                            ("garantia", "Certificado de Garantia"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.produtofabricado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="componente",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.produtofabricado"
            ),
        ),
        migrations.CreateModel(
            name="SaidaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Enviada"),
                ),
                ("cliente", models.CharField(max_length=200, verbose_name="Cliente")),
                (
                    "nota_fiscal",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notas_fiscais/",
                        verbose_name="Nota Fiscal",
                    ),
                ),
                (
                    "foto_saida",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_saidas/",
                        verbose_name="Foto da Saída",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Saída"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.produtofabricado",
                        verbose_name="Produto Enviado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável pela Saída",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_documento",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_documentos/",
                        verbose_name="Foto da Nota Fiscal/Documento",
                    ),
                ),
                (
                    "foto_embalagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fotos_embalagens/",
                        verbose_name="Foto da Embalagem",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Recebimento"
                    ),
                ),
                (
                    "descricao_pacote",
                    models.TextField(verbose_name="Descrição do Pacote"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações Gerais"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando Armazenamento"),
                            ("armazenado", "Armazenado"),
                            ("concluido", "Concluído"),
                        ],
                        default="aguardando",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.setor",
                        verbose_name="Setor de Destino",
                    ),
                ),
            ],
        ),
    ]
