# Generated by Django 5.2.6 on 2025-09-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemestoque",
            name="documentacao",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos_itens/",
                verbose_name="Documentação",
            ),
        ),
        migrations.AddField(
            model_name="produtofabricado",
            name="documentacao_tecnica",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos_produtos/",
                verbose_name="Documentação Técnica",
            ),
        ),
        migrations.CreateModel(
            name="ImagemItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_itens/")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.itemestoque",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_produtos/")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.produtofabricado",
                    ),
                ),
            ],
        ),
    ]
