# Generated by Django 5.2.6 on 2025-09-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recebimento",
            name="descricao_pacote",
        ),
        migrations.AddField(
            model_name="recebimento",
            name="fornecedor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Fornecedor/Empresa que Entregou",
            ),
        ),
        migrations.AddField(
            model_name="recebimento",
            name="numero_nota_fiscal",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Número da Nota Fiscal",
            ),
        ),
    ]
