# Generated by Django 5.2.6 on 2025-09-28 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "verbose_name": "Empresa / Mercado",
                "verbose_name_plural": "Empresas / Mercados",
            },
        ),
    ]
