# Generated by Django 5.2.6 on 2025-09-24 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.CharField(max_length=200, verbose_name="Cliente/Destino"),
                ),
                (
                    "data_expedicao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Expedição"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável pela Expedição",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoExpedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.FileField(upload_to="documentos_expedicao/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nota_fiscal", "Nota Fiscal"),
                            ("comprovante", "Comprovante de Entrega"),
                            ("ordem_envio", "Ordem de Envio"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.expedicao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemExpedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.expedicao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.produtofabricado",
                    ),
                ),
            ],
        ),
    ]
