# Generated by Django 5.2.6 on 2025-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_expedicao_documentoexpedicao_itemexpedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedicao",
            name="nota_fiscal",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notas_fiscais_saida/",
                verbose_name="Nota Fiscal",
            ),
        ),
    ]
