# Generated by Django 5.2.6 on 2025-09-28 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_empresa_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfilusuario",
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuário",
            },
        ),
        migrations.DeleteModel(
            name="SaidaProduto",
        ),
    ]
