# Generated by Django 5.2.6 on 2025-09-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_itemestoque_documentacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtofabricado",
            name="documentacao_tecnica",
        ),
        migrations.CreateModel(
            name="DocumentoProdutoFabricado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.FileField(upload_to="documentos_produtos/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Manual de Instruções"),
                            ("instalacao", "Guia de Instalação"),
                            ("erro", "Documento de Erros e Correções"),
                            ("manutencao", "Guia de Manutenção"),
                            ("garantia", "Certificado de Garantia"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="core.produtofabricado",
                    ),
                ),
            ],
        ),
    ]
