# Generated by Django 5.2.6 on 2025-09-30 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_kanbancolumn_task_taskquantidadefeita"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="data_finalizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TaskHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("criado", "Criado"),
                            ("movido", "Movido"),
                            ("editado", "Editado"),
                            ("iniciado", "Iniciado"),
                            ("finalizado", "Finalizado"),
                            ("quantidade_adicionada", "Quantidade Adicionada"),
                            ("responsavel_adicionado", "Responsável Adicionado"),
                            ("responsavel_removido", "Responsável Removido"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="core.task",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico da Tarefa",
                "verbose_name_plural": "Históricos das Tarefas",
                "ordering": ["-data"],
            },
        ),
    ]
