# Generated by Django 5.2.6 on 2025-09-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_recebimento_descricao_pacote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recebimento",
            name="status",
            field=models.CharField(
                choices=[("aguardando", "Aguardando"), ("entregue", "Entregue")],
                default="aguardando",
                max_length=20,
            ),
        ),
    ]
