# Generated by Django 5.2.6 on 2025-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_task_data_finalizacao_task_finalizado_taskhistorico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="quantidade",
        ),
        migrations.AddField(
            model_name="task",
            name="quantidade_meta",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade Meta"
            ),
        ),
    ]
