# Generated by Django 5.2.6 on 2025-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_expedicao_nota_fiscal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedicao",
            name="nota_fiscal",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Número da Nota Fiscal",
            ),
        ),
    ]
