# Generated by Django 5.2.6 on 2025-09-30 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_task_quantidade_task_quantidade_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JornadaTrabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horas_diarias",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=4,
                        verbose_name="Horas Diárias",
                    ),
                ),
                (
                    "dias_semana",
                    models.CharField(
                        default="1,2,3,4,5",
                        help_text="0=Dom, 1=Seg, 2=Ter, 3=Qua, 4=Qui, 5=Sex, 6=Sáb",
                        max_length=50,
                        verbose_name="Dias da Semana",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jornada",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada de Trabalho",
                "verbose_name_plural": "Jornadas de Trabalho",
            },
        ),
        migrations.CreateModel(
            name="RegistroPonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                ("data_hora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "localizacao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Localização",
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ponto",
                "verbose_name_plural": "Registros de Ponto",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="ResumoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                (
                    "horas_trabalhadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "horas_esperadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "saldo_horas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("dias_presentes", models.IntegerField(default=0)),
                ("dias_ausentes", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumos_mensais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumo Mensal",
                "verbose_name_plural": "Resumos Mensais",
                "ordering": ["-ano", "-mes"],
                "unique_together": {("usuario", "mes", "ano")},
            },
        ),
    ]
