# Generated by Django 5.2.6 on 2025-09-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_expedicao_nota_fiscal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagemExpedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="imagens_expedicao/")),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="core.expedicao",
                    ),
                ),
            ],
        ),
    ]
