# Generated by Django 5.2.6 on 2025-09-25 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_imagemexpedicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recebimento",
            name="data_cotacao",
        ),
    ]
