# Generated by Django 5.2.6 on 2025-09-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_jornadatrabalho_registroponto_resumomensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="jornadatrabalho",
            name="horas_sexta",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                max_digits=4,
                verbose_name="Horas na Sexta",
            ),
        ),
        migrations.AddField(
            model_name="jornadatrabalho",
            name="intervalo_almoco",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=3,
                verbose_name="Intervalo de Almoço (horas)",
            ),
        ),
        migrations.AlterField(
            model_name="jornadatrabalho",
            name="dias_semana",
            field=models.CharField(
                default="0,1,2,3,4",
                help_text="0=Seg, 1=Ter, 2=Qua, 3=Qui, 4=Sex, 5=Sáb, 6=Dom",
                max_length=50,
                verbose_name="Dias da Semana",
            ),
        ),
        migrations.AlterField(
            model_name="jornadatrabalho",
            name="horas_diarias",
            field=models.DecimalField(
                decimal_places=2,
                default=9.0,
                max_digits=4,
                verbose_name="Horas Diárias (padrão)",
            ),
        ),
        migrations.AlterField(
            model_name="registroponto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("saida", "Saída"),
                    ("inicio_almoco", "Início Almoço"),
                    ("fim_almoco", "Fim Almoço"),
                ],
                max_length=15,
            ),
        ),
    ]
