# Generated by Django 5.2.6 on 2025-09-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_recebimento_data_cotacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtofabricado",
            name="item_associado",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receita",
                to="core.itemestoque",
            ),
        ),
    ]
