# Generated by Django 5.2.6 on 2025-10-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_movimentacaoestoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfornecedor",
            name="fornecedor_nome",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Fornecedor"
            ),
        ),
        migrations.AlterField(
            model_name="itemfornecedor",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fornecedor",
            ),
        ),
    ]
