# Generated by Django 5.2.6 on 2025-10-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_itemfornecedor_fornecedor_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recebimento",
            name="fornecedor_nome",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Fornecedor"
            ),
        ),
    ]
