# Generated by Django 5.2.6 on 2025-10-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_recebimento_fornecedor_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registroponto",
            name="abonado",
            field=models.BooleanField(default=False, verbose_name="Abonado"),
        ),
        migrations.AddField(
            model_name="registroponto",
            name="abonado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abonos_concedidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Abonado por",
            ),
        ),
        migrations.AddField(
            model_name="registroponto",
            name="data_abono",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data do Abono"
            ),
        ),
        migrations.AddField(
            model_name="registroponto",
            name="motivo_abono",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo do Abono"
            ),
        ),
        migrations.CreateModel(
            name="AbonoDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data do Abono")),
                (
                    "tipo_abono",
                    models.CharField(
                        choices=[
                            ("doenca", "Doença"),
                            ("atestado", "Atestado Médico"),
                            ("falta_justificada", "Falta Justificada"),
                            ("licenca", "Licença"),
                            ("ferias", "Férias"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Abono",
                    ),
                ),
                ("motivo", models.TextField(verbose_name="Motivo/Justificativa")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "horas_abonadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=4,
                        verbose_name="Horas Abonadas",
                    ),
                ),
                (
                    "abonado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abonos_dias_concedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Abonado por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos_dias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de Dia",
                "verbose_name_plural": "Abonos de Dias",
                "ordering": ["-data"],
                "unique_together": {("usuario", "data")},
            },
        ),
    ]
