# Generated by Django 5.2.6 on 2025-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_registroponto_abonado_registroponto_abonado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jornadatrabalho",
            name="dia_fim_mes",
            field=models.IntegerField(
                default=0,
                help_text="Dia do mês em que termina o período (0=último dia do mês)",
                verbose_name="Dia de Fim do Mês",
            ),
        ),
        migrations.AddField(
            model_name="jornadatrabalho",
            name="dia_inicio_mes",
            field=models.IntegerField(
                default=1,
                help_text="Dia do mês em que inicia o período (1-31)",
                verbose_name="Dia de Início do Mês",
            ),
        ),
    ]
