# Generated by Django 5.2.6 on 2025-10-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_jornadatrabalho_dia_fim_mes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Data de Cadastro"
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="endereco",
            field=models.TextField(blank=True, null=True, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="mercado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eletronico", "Eletrônico"),
                    ("metalurgica", "Metalúrgica"),
                    ("textil", "Têxtil"),
                    ("plastico", "Plástico"),
                    ("madeira", "Madeira"),
                    ("quimico", "Químico"),
                    ("alimenticio", "Alimentício"),
                    ("farmaceutico", "Farmacêutico"),
                    ("construcao", "Construção"),
                    ("automotivo", "Automotivo"),
                    ("tecnologia", "Tecnologia"),
                    ("servicos", "Serviços"),
                    ("outro", "Outro"),
                ],
                max_length=50,
                null=True,
                verbose_name="Mercado de Atuação",
            ),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="site",
            field=models.URLField(blank=True, null=True, verbose_name="Site"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="link_site",
            field=models.URLField(
                blank=True, null=True, verbose_name="Website (deprecated)"
            ),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="nome",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "endereco",
                    models.TextField(blank=True, null=True, verbose_name="Endereço"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Site")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "mercado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("eletronico", "Eletrônico"),
                            ("metalurgica", "Metalúrgica"),
                            ("textil", "Têxtil"),
                            ("plastico", "Plástico"),
                            ("madeira", "Madeira"),
                            ("quimico", "Químico"),
                            ("alimenticio", "Alimentício"),
                            ("farmaceutico", "Farmacêutico"),
                            ("construcao", "Construção"),
                            ("automotivo", "Automotivo"),
                            ("tecnologia", "Tecnologia"),
                            ("servicos", "Serviços"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Mercado de Atuação",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.empresa"
                    ),
                ),
                (
                    "produtos_fornecidos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clientes",
                        to="core.itemestoque",
                        verbose_name="Produtos que Fornecemos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
                "unique_together": {("empresa", "nome")},
            },
        ),
    ]
