# Generated by Django 5.2.6 on 2025-10-24 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_fornecedor_options_fornecedor_data_cadastro_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisicaoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200, verbose_name="Item")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantidade"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        default="un", max_length=20, verbose_name="Unidade"
                    ),
                ),
                (
                    "preco_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço Estimado (R$)",
                    ),
                ),
                (
                    "proposito",
                    models.CharField(max_length=200, verbose_name="Propósito"),
                ),
                (
                    "projeto",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Projeto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando Aprovação"),
                            ("aprovado", "Aprovado - Aguardando Compra"),
                            ("comprado", "Comprado - Aguardando Recebimento"),
                            ("recebido", "Pedido Concluído"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_requisicao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Requisição"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "observacao_aprovacao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação da Aprovação"
                    ),
                ),
                (
                    "data_compra",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Compra"
                    ),
                ),
                (
                    "preco_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço Real (R$)",
                    ),
                ),
                (
                    "nota_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nota Fiscal",
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "observacao_recebimento",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação do Recebimento"
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_compra",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado Por",
                    ),
                ),
                (
                    "comprado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comprado Por",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "recebido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos_compra",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recebido Por",
                    ),
                ),
                (
                    "requerente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisicoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requerente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de Compra",
                "verbose_name_plural": "Requisições de Compra",
                "ordering": ["-data_requisicao"],
            },
        ),
    ]
