# Generated by Django 5.2.6 on 2025-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_requisicaocompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaocompra",
            name="documento_aprovacao",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="requisicoes/aprovacao/",
                verbose_name="Documento/Imagem de Aprovação",
            ),
        ),
    ]
