# Generated by Django 5.2.6 on 2025-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_requisicaocompra_documento_aprovacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisicaocompra",
            name="data_entrega_prevista",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Entrega Prevista"
            ),
        ),
    ]
