# Generated by Django 5.2.6 on 2025-10-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_requisicaocompra_data_entrega_prevista"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoRequisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Alteração"
                    ),
                ),
                (
                    "tipo_alteracao",
                    models.CharField(max_length=100, verbose_name="Tipo de Alteração"),
                ),
                (
                    "descricao",
                    models.TextField(verbose_name="Descrição das Alterações"),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="core.requisicaocompra",
                        verbose_name="Requisição",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Requisição",
                "verbose_name_plural": "Históricos de Requisições",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
