# Generated by Django 5.2.6 on 2025-10-24 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_historicorequisicao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GastoCaixaInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gastos_caixa/",
                        verbose_name="Comprovante/Foto",
                    ),
                ),
                (
                    "data_gasto",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Gasto"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto de Caixa Interno",
                "verbose_name_plural": "Gastos de Caixa Interno",
                "ordering": ["-data_gasto"],
            },
        ),
        migrations.CreateModel(
            name="GastoViagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="gastos_viagem/",
                        verbose_name="Comprovante/Foto",
                    ),
                ),
                (
                    "data_gasto",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Gasto"
                    ),
                ),
                (
                    "data_viagem",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Viagem"
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Destino"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto de Viagem",
                "verbose_name_plural": "Gastos de Viagem",
                "ordering": ["-data_gasto"],
            },
        ),
    ]
