# Generated by Django 5.2.6 on 2025-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_gastoviagem_categoria_nota_fiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastoviagem",
            name="enviado_financeiro",
            field=models.BooleanField(
                default=False, verbose_name="Enviado ao Financeiro"
            ),
        ),
    ]
