# Generated by Django 5.2.6 on 2025-11-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_gastoviagem_enviado_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemestoque",
            name="links",
            field=models.TextField(
                blank=True,
                help_text="Links úteis (um por linha)",
                null=True,
                verbose_name="Links",
            ),
        ),
    ]
