# Generated by Django 5.2.6 on 2026-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_itemestoque_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_financeiro',
            field=models.BooleanField(default=False, verbose_name='É do Financeiro'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='dias_aviso_pagamento',
            field=models.IntegerField(blank=True, default=3, help_text='Quantos dias antes do vencimento enviar alerta', null=True, verbose_name='Dias de Antecedência para Aviso'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='dias_pagamento',
            field=models.TextField(blank=True, help_text="Exemplo: '15, 30, 45' ou '29 de fevereiro'", null=True, verbose_name='Dias de Pagamento'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='documento_boleto',
            field=models.FileField(blank=True, null=True, upload_to='requisicoes/boletos/', verbose_name='Documento do Boleto'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='documento_nota_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='requisicoes/notas_fiscais/', verbose_name='Documento da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('transferencia_bancaria', 'Transferência Bancária'), ('boleto', 'Boleto'), ('cartao', 'Cartão')], max_length=30, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='link_item',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Item'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='quantidade_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Parcelas'),
        ),
    ]
