# Generated by Django 5.2.6 on 2026-02-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_perfilusuario_is_financeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaocompra',
            name='fornecedor_nome_digitado',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Fornecedor (digitado)'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='tipo_dias_pagamento',
            field=models.CharField(blank=True, choices=[('15_em_15', 'De 15 em 15 dias'), ('30_em_30', 'De 30 em 30 dias'), ('especificos', 'Dias específicos')], max_length=20, null=True, verbose_name='Tipo de Dias de Pagamento'),
        ),
    ]
