# Generated by Django 5.2.6 on 2026-02-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_requisicaocompra_fornecedor_nome_digitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaocompra',
            name='projeto',
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes', to='core.produtofabricado', verbose_name='Produto'),
        ),
    ]
