# Generated by Django 5.2.6 on 2026-02-13 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_requisicaocompra_projeto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(verbose_name='Número da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes_boleto/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_pagos', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_boleto', to='core.requisicaocompra', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Parcela de Boleto',
                'verbose_name_plural': 'Parcelas de Boleto',
                'ordering': ['data_vencimento', 'numero_parcela'],
                'unique_together': {('requisicao', 'numero_parcela')},
            },
        ),
    ]
