# Generated by Django 5.2.6 on 2026-02-16 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_perfilusuario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#6366f1', max_length=20, verbose_name='Cor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Milestone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('cor', models.CharField(default='#10b981', max_length=20, verbose_name='Cor')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='planejado', max_length=20, verbose_name='Status')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['ordem', 'data_fim'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Label')),
                ('cor', models.CharField(default='#6b7280', max_length=20, verbose_name='Cor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.project')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['nome'],
                'unique_together': {('project', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Automação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('trigger_type', models.CharField(choices=[('status_changed', 'Status Alterado'), ('task_created', 'Tarefa Criada'), ('task_assigned', 'Tarefa Atribuída'), ('due_date_approaching', 'Prazo Próximo'), ('task_overdue', 'Tarefa Atrasada')], max_length=50, verbose_name='Tipo de Gatilho')),
                ('trigger_value', models.JSONField(blank=True, null=True, verbose_name='Configuração do Gatilho')),
                ('action_type', models.CharField(choices=[('set_status', 'Definir Status'), ('assign_user', 'Atribuir Usuário'), ('add_label', 'Adicionar Label'), ('move_to_sprint', 'Mover para Sprint'), ('send_notification', 'Enviar Notificação')], max_length=50, verbose_name='Tipo de Ação')),
                ('action_value', models.JSONField(blank=True, null=True, verbose_name='Configuração da Ação')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Sprint')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo do Sprint')),
                ('ativo', models.BooleanField(default=False, verbose_name='Sprint Ativo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='core.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-data_inicio'],
                'unique_together': {('project', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridade')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('estimativa', models.DecimalField(blank=True, decimal_places=2, help_text='Horas ou Story Points', max_digits=10, null=True, verbose_name='Estimativa')),
                ('quantidade_meta', models.PositiveIntegerField(default=0, help_text='Quantidade a produzir', verbose_name='Quantidade Meta')),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('in_progress', 'Em Progresso'), ('review', 'Em Revisão'), ('done', 'Concluído'), ('blocked', 'Bloqueado')], default='todo', max_length=20, verbose_name='Status')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='core.label', verbose_name='Labels')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.milestone', verbose_name='Milestone')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.projecttask', verbose_name='Tarefa Pai')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project', verbose_name='Projeto')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.sprint', verbose_name='Sprint')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['ordem', '-criado_em'],
                'indexes': [models.Index(fields=['project', 'status'], name='core_projec_project_8400ef_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='core_projec_data_in_3d73da_idx')],
            },
        ),
    ]
