# Generated by Django 5.2.6 on 2026-02-16 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_project_milestone_label_projectautomation_sprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='coluna',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsaveis',
        ),
        migrations.AlterField(
            model_name='taskhistorico',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.projecttask', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='taskquantidadefeita',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantidades_feitas', to='core.projecttask', verbose_name='Tarefa'),
        ),
        migrations.AlterModelOptions(
            name='taskhistorico',
            options={'ordering': ['-data'], 'verbose_name': 'Histórico de Tarefa', 'verbose_name_plural': 'Histórico de Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='taskquantidadefeita',
            options={'ordering': ['-data'], 'verbose_name': 'Quantidade Produzida', 'verbose_name_plural': 'Quantidades Produzidas'},
        ),
        migrations.AddField(
            model_name='taskquantidadefeita',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='taskhistorico',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='taskhistorico',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='taskhistorico',
            name='tipo_acao',
            field=models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('movido', 'Movido para outro milestone'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado'), ('reaberto', 'Reaberto'), ('bloqueado', 'Bloqueado'), ('desbloqueado', 'Desbloqueado'), ('quantidade_adicionada', 'Quantidade Adicionada'), ('responsavel_adicionado', 'Responsável Adicionado'), ('responsavel_removido', 'Responsável Removido'), ('label_adicionada', 'Label Adicionada'), ('label_removida', 'Label Removida'), ('prazo_alterado', 'Prazo Alterado'), ('priority_alterada', 'Prioridade Alterada'), ('subtask_criada', 'Subtarefa Criada')], max_length=30, verbose_name='Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='taskhistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='taskquantidadefeita',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='taskquantidadefeita',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='taskquantidadefeita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='KanbanColumn',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
