# Generated by Django 5.2.6 on 2026-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_emprestimoitem_perfilusuario_is_estoquista'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='local_armazenamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Armazenamento (legado)'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('tarefa_atribuida', 'Tarefa Atribuída'), ('tarefa_concluida', 'Tarefa Concluída'), ('prazo_proximo', 'Prazo Próximo'), ('tarefa_atrasada', 'Tarefa Atrasada'), ('comentario', 'Novo Comentário'), ('emprestimo_atrasado', 'Empréstimo Atrasado'), ('emprestimo_novo', 'Novo Empréstimo')], max_length=30, verbose_name='Tipo'),
        ),
    ]
