# Generated by Django 5.2.6 on 2026-04-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_itemestoque_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série'),
        ),
    ]
