- name: SSH agent
  uses: webfactory/ssh-agent@v0.9.0
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Add known_hosts
  run: |
    mkdir -p ~/.ssh
    ssh-keyscan -H 168.231.92.3 >> ~/.ssh/known_hosts

- name: Run remote deploy
  run: |
    ssh -o StrictHostKeyChecking=yes django_user@168.231.92.3 '/home/django_user/blockline_app/deploy.sh'
